### ISSUE TITLE
Upload assets

### ISSUE THREAD

**Issue by emilyb7** [CYPIAPT-LNDSE/goals-app#106]
Hey Noga,

Can you please send us all the assets that are new?

Right now I'm looking for:
- The logo in the header
- The menu icon
- The back icon

Will probably add more things to this list as they come up...

Thank you!

**Comment by nogainbar** [comment]
yes! will do it now!

**Comment by emilyb7** [comment]
Links to material icons:

https://material.io/icons/#ic_delete
https://material.io/icons/#ic_mode_edit
https://material.io/icons/#ic_keyboard_arrow_left
https://material.io/icons/#ic_close

All other assets in G-Drive!
