### ISSUE TITLE
QA Process

### ISSUE THREAD

**Issue by des-des** [CYPIAPT-LNDSE/goals-app#109]
+ Code needs to be tested
 + I will look at pulls once a day at a minimum, but normally will review a request within a couple of hours
 + Small pull requests are better
 + Try to branch off master when starting your next piece of work. I will not look at a pull request that is branched of another pull that is not merged. This is because otherwise I will end up looking at the same diff twice.
 + If there are commits already in master visible on a pull request it needs to be merged locally with master (Does that make sense?)
 + commit often, make sure commit messages have issue numbers in them
 + make pull requests often (small pulls are best). If you find yourself working on a pull for many days, try to step back from your problem and break it down into smaller parts.
 + You should leave it to me to merge pulls into master
 + I will normally be available between 730am - 4pm but may sometimes check pulls around 8pm.
 + Set up travis.
 + Think about your tests before you write them. They should give you confidence that you program works.

That's it for now, I hope this all sounds alright!

**Comment by emilyb7** [comment]
Sounds good, Eoin, but you are not going to like how much code I am planning on PR-ing soon. I've been waiting for @shiryz to get a chance to review it first...

Also, Shireen and I talked about keeping our frontend and backend separate for now. So we would have a kind of frontend and backend master. This doesn't really fit in with your QA process. Should we scrap that idea? Or would it be ok if I assigned PRs to the frontend master to you too?

**Comment by des-des** [comment]
@emilyb7 Can you explain a bit why you are keeping them separate?

**Comment by emilyb7** [comment]
@des-des mostly because for the moment they don't need to be merged. And then we can do all the merging when we are sitting next to each other instead of remotely.
Also we're not sure yet about how the frontend and backend are going to communicate with each other. We've talked about web sockets but need to figure this out!

**Comment by des-des** [comment]
@emilyb7 @shiryz I think you should keep everything in one master branch. If you get your file structure right, you should be able to work on these separately. 

Things should be merged into master as quickly as poss! Pull request backlog === bad
