### ISSUE TITLE
REVISED mockups for app!

### ISSUE THREAD

**Issue by emilyb7** [CYPIAPT-LNDSE/goals-app#11]
After talking to @nogainbar we decided to focus our designs on a single theme. We would like to propose a garden-related theme for this week's prototype (there are nice ways to do simple flower-related animations). If we had more time, we could probably make this a bit more open.

We have drawn inspiration from [forest](https://www.forestapp.cc/en/) - this is an app that lets you set goals and as you complete goals you grow your forest ecosystem. It tells a nice story.

In a similar way, we would grow our garden.

User journey:

1. Stage 1 - user can see all their goals in one view (to be determined: can the user see some kind of measure of their recent progress at this stage? - @amgoforth )

2. Stage 2 - user can add a new goal, they can choose a colour for their goal (/flower)

3. Stage 3 - user can rate their progress - we will do our best to put together a kind of flower-growing animation in the chosen color; this would be accompanied by a sliding scale so that we can show numerical values

4. Stage 4 - user can review their recent progress - show a collection of flowers from the last week

**Comment by shiryz** [comment]
![20170130_165257](https://cloud.githubusercontent.com/assets/22002193/22432703/abff9e6a-e70d-11e6-9626-8cfac0ea76b7.jpg)
