### ISSUE TITLE
Hangouts link to use for standups

### ISSUE THREAD

**Issue by shiryz** [CYPIAPT-LNDSE/goals-app#116]
https://hangouts.google.com/call/khiy3uue2fg37fk2rkuovchneef

**Comment by emilyb7** [comment]
@amgoforth, you weren't there!

But no worries, I don't think either of us have much news. I've been working on making the list of goals look nice. Here's a screenshot of the latest effort:

<img width="342" alt="screen shot 2017-03-09 at 10 36 49" src="https://cloud.githubusercontent.com/assets/17532458/23751880/18836640-04cb-11e7-937f-1bab1afbb482.png">

Today I'll probably be working on refactoring some of yesterday's code. Shireen is setting up our database.

If you have any questions, please let us know!

**Comment by amgoforth** [comment]
Ugh, sorry.  That looks great!  I managed to double book myself, and am actually (and have been) in a meeting witu Dan about the next Hackathon!  Tomorrow I have time between 11-3pm

**Comment by emilyb7** [comment]
11.30 or 12 would be good for me tomorrow!

**Comment by shiryz** [comment]
11:30 would be great! I think we can use this link for all standups.

**Comment by emilyb7** [comment]
@amgoforth 

sorry for the lack of communication since last week.

I was talking to @nogainbar and she suggested that one hangout per day might be a bit too much for us all. Two per week might be more effective.

Do you have time for a catchup tomorrow?

Shireen and I are both available all day.

**Comment by amgoforth** [comment]
Can you do tomorrow afternoon? 4pm?

Alex Goforth

London & South East Children & Young People’s IAPT Collaborative Programme Lead

Direct Line – 020 7443 2299
Mobile – 07776 760884

 




-----Original Message-----

**Comment by emilyb7** [comment]
@amgoforth afraid not, I'm going to be on a plane to Israel! I think Shireen and I can both do Thursday though.

**Comment by shiryz** [comment]
Yup Thursday is good :+1:

**Comment by amgoforth** [comment]
2:30pm?

All the best

Alex
________________________________
Alex Goforth
Programme Lead
London & South East Children & Young People’s IAPT Collaborative
Direct Line 020 7443 2299, Mobile 07776 760884
Twitter @LDNSECYPIAPT
YouTube Channel<https://www.youtube.com/channel/UCoqZ4I8IEq8hB1-oi6UhNCw>
Learning Collaborative website<https://cypiapt.wordpress.com/>
________________________________
[cid:image2f0891.JPG@91528952.4bb5d440]

www.annafreud.org<http://www.annafreud.org/>             +44 (0)20 7794 2313






________________________________

**Comment by amgoforth** [comment]
Apols, can we change this to 3:30 please?

**Comment by shiryz** [comment]
@amgoforth , yup good for me .

**Comment by amgoforth** [comment]
@bradreeder @shiryz @emilyb7 shall we use the link above?

**Comment by shiryz** [comment]
@amgoforth  yes :smile:

**Comment by emilyb7** [comment]
@amgoforth yes we're there now!

**Comment by amgoforth** [comment]
I am try9ing to join but not working on laptop – trying phone insytead

All the best

Alex
________________________________
Alex Goforth
Programme Lead
London & South East Children & Young People’s IAPT Collaborative
Direct Line 020 7443 2299, Mobile 07776 760884
Twitter @LDNSECYPIAPT
YouTube Channel<https://www.youtube.com/channel/UCoqZ4I8IEq8hB1-oi6UhNCw>
Learning Collaborative website<https://cypiapt.wordpress.com/>
________________________________
[cid:image2f0891.JPG@91528952.4bb5d440]

www.annafreud.org<http://www.annafreud.org/>             +44 (0)20 7794 2313






________________________________

**Comment by shiryz** [comment]
Closing as the standups have happened.
