### ISSUE TITLE
Proposed colour scheme

### ISSUE THREAD

**Issue by emilyb7** [CYPIAPT-LNDSE/goals-app#12]
Something along these lines (we need natural colours)

https://color.adobe.com/create/color-wheel/?base=2&rule=Analogous&selected=3&name=My%20Color%20Theme&mode=rgb&rgbvalues=0.9058823529411765,0.8510790378311822,0.6274509803921569,0.834313725490196,0.2701303417737782,0.3192678827968954,0.3411764705882353,0.4566666666665788,0.85,0.5764705882352941,0.8156862745098039,0.5843137254901961,0.9,0.7015430745514502,0.31624567474048443&swatchOrder=0,1,2,3,4

**Comment by amgoforth** [comment]
I agree with natural colours that match the theme of nature, but I prefer colours that are a little more vivid than these if possible.

**Comment by emilyb7** [comment]
@amgoforth we're open to  suggestions if you want to play around with the colours!

**Comment by MHemsley** [comment]
Just to provide some info on previous user experience workshops with this user group, they really like stronger, vivid colours, with use of white space or black space to make it less overwhelming, apps that have tested well, citymapper, spotify, breathe with me

**Comment by emilyb7** [comment]
@amgoforth @MHemsley new ideas!

https://coolors.co/export/png/fcfc62-86e889-fc6dab-f1ffe7-2364aa

https://coolors.co/export/png/abff4f-090446-f21b3f-f7ebec-31cb00

**Comment by amgoforth** [comment]
@emilyb7 @MHemsley Thanks! I think I like the one above starting with fcfc62.

**Comment by emilyb7** [comment]
great, we're going for the \#fcfc62 option 👍

**Comment by emilyb7** [comment]
@amgoforth we're coming back to this...

here's an idea of what the goals page could look like with your chosen color scheme (things can be moved around though)

Shireen is going to post an alternative... let us know if you have a preference!

<img width="708" alt="screen shot 2017-02-01 at 12 11 20" src="https://cloud.githubusercontent.com/assets/17532458/22506306/a18dda58-e877-11e6-97ae-0862f69bc386.png">

**Comment by shiryz** [comment]
![screenshot from 2017-02-01 12-08-33](https://cloud.githubusercontent.com/assets/22002193/22506240/489a834c-e877-11e6-9f77-750465cd1a49.png)

**Comment by emilyb7** [comment]
@nogainbar has some more ideas, so we're holding off on this one for now...
