### ISSUE TITLE
Sprint retrospective

### ISSUE THREAD

**Issue by MHemsley** [CYPIAPT-LNDSE/goals-app#123]
Hi all,

It would be good to get a time in to have a sprint retro towards the end of this week (Friday morning?)

The purpose of this will be to cover the broad points:
What went well during this sprint?
What could have been done better during the sprint?
What additional support would have been helpful?
What could we do differently to improve?

This process should not be accusational, but should facilitate communication to improve team effectiveness within the next sprint, and to facilitate personal development.

**Comment by bradreeder** [comment]
Hi @MHemsley , I'm going to be away in Sussex this Friday. I'd be available to do retrospectives on Monday next week (or thursday). The teams started on Tuesday last week so it might be closer to a full-sprint for them but I will leave it to @emilyb7 & @shiryz 's preference.

**Comment by emilyb7** [comment]
I would prefer next Thursday. We're not due to finish the sprint until weds anyway.

**Comment by shiryz** [comment]
I'm flexible, I would prefer Tuesday though.

**Comment by MHemsley** [comment]
I'm away next week, but happy for @bradreeder to lead this in my absence and catch me up on my return
