### ISSUE TITLE
Final piece of redux setup

### ISSUE THREAD

**Issue by des-des** [CYPIAPT-LNDSE/goals-app#124]
Okay so we are pretty much there getting redux set up properly, I thought I would point out one last thing.

  1. Each view can be a container
  2. Each view can have its own actions file (if you want to reuse action creators you can import them in each views action file..)
  3. For each view / container we can go `import * as actionCreators` from '../actions/{nameOfView}.js'. The we do not need to make a mapDispatchToProps, just pass in actionCreators as the second argument of the connect function.

So in our app we have
app
|--containers
  |--main_containers.js
  |--add_goal.js
  |--goals_list.js
|--actions
  |--add_goal.js
  |--goals_list.js
|--components
  |--add_goal
    |--..

You may have logic shared between views, so you might want an action file that gets imported into the action files specific to views, you might want a reducer file per view, but also you might now, it depends on how separate the data is here..

**Comment by emilyb7** [comment]
@des-des 

> Each view can be a container

does that mean it *should* be a container? or are we ok as we are?

i've spent a lot of time on the redux setup and would prefer to stick to getting the essential stuff done!

having an actions file seems sensible though...

**Comment by des-des** [comment]
@emilyb7 ok this seems okay

**Comment by emilyb7** [comment]
@des-des... like, 6 weeks later, I've suddenly understood what you mean by 
> The we do not need to make a mapDispatchToProps, just pass in actionCreators as the second argument of the connect function.

Have now fixed this for 1 / 2 containers, see #261 (haven't assigned you for review yet because I need to change some more stuff...).

Is it possible / appropriate to do something similar in place of `mapStateToProps` and / or the propTypes validation? For instance, have one file that's like an index of all the possible props?

**Comment by emilyb7** [comment]
Also this is clearly maybe a bit pointless since we've nearly finished... but would be nice to know how to do it better...

**Comment by des-des** [comment]
@emilyb7 Sorry, I probable could have explained better.

There is not a generic way of doing the same with mapStateToProps.

I am sure if you see repetition there, you can build some simple helpers to refactor this out.
