### ISSUE TITLE
We are live!

### ISSUE THREAD

**Issue by emilyb7** [CYPIAPT-LNDSE/goals-app#136]
Hey @amgoforth 

Thought you might want to check out our progress before the hangout today.

We've deployed a semi-working version here. You can click through adding a goal, but it doesn't actually do much else.

https://polar-dawn-55555.herokuapp.com/

At the moment, this is running in the browser only. So although it looks like you can add a goal, if you refresh the page the goal will have disappeared again.

**Comment by emilyb7** [comment]
@amgoforth heroku has been updated if you want to take another look!

**Comment by emilyb7** [comment]
@amgoforth check again for cactus-themed animation!

**Comment by emilyb7** [comment]
@amgoforth i've just looked at the app on my own phone and have to admit, it looks awful!

For user testing I would recommend using the mobile phone simulator tool in chrome (so on a laptop or desktop). iPhone 5 looks best.

Alternatively, if you have access to an actual iPhone 5 then that would hopefully also be fine!

Let me know if you have serious problems!

**Comment by amgoforth** [comment]
Good advice!
