### ISSUE TITLE
Assets we need

### ISSUE THREAD

**Issue by emilyb7** [CYPIAPT-LNDSE/goals-app#145]
- arrow on line chart
- redder looking chilli pepper
- 2 missing images for goal tiles (cactus and flower)
- favicon
- splash screen logo
- svgs for line chart nodes (for each avatar)

**Comment by nogainbar** [comment]
Hey all! Still in Lisbon but will do it all tomorrow!! 😘

**Comment by emilyb7** [comment]
Thank you! 💛 hope you're having fun!

**Comment by nogainbar** [comment]
Hey all!

so

- arrow on line chart is a material design one: https://material.io/icons/#ic_keyboard_arrow_right
- redder looking chilli pepper: DONE
- 2 missing images for goal tiles (cactus and flower): DONE
- favicon: done!
- splash screen logo: still in progress..
- Plants for chart: done 

:)

**Comment by nogainbar** [comment]
Added a splash page https://drive.google.com/open?id=0B24Sdkg-P6MnSDVkVjJSaFBPTW8

closing this issue as all checked.

**Comment by emilyb7** [comment]
@nogainbar we ❤️ it!
