### ISSUE TITLE
Choice of favicons 🌻

### ISSUE THREAD

**Issue by emilyb7** [CYPIAPT-LNDSE/goals-app#165]
[drive-download-20170321T105937Z-001.zip](https://github.com/CYPIAPT-LNDSE/goals-app/files/857863/drive-download-20170321T105937Z-001.zip)

Let us know which one you like best :)

**Comment by nogainbar** [comment]
ill just drop it here, my favourite one is FAVICON_TREE_2 but no pressure! ;) hehe.
