### ISSUE TITLE
Retrospective today?

### ISSUE THREAD

**Issue by emilyb7** [CYPIAPT-LNDSE/goals-app#178]
@amgoforth I think we might have confused the times of the planned meeting today. Shireen and I were on hangouts at 1.30pm, but I'm now starting to think that we said 1pm and that's why no one was there.
Sorry if we messed up.
Can we rearrange for next week?
Hope user testing goes well!

**Comment by amgoforth** [comment]
I could do between 10-1pm on Tuesday 28th or 2:30-5pm on Friday 31st March.  Do those work for you?

**Comment by bradreeder** [comment]
@amgoforth My schedule is flexible and I'm happy with either of those. 

@shiryz @emilyb7 @nogainbar No worries. Let me know your availability and happy to go with what suits.

**Comment by emilyb7** [comment]
ok, we would like to do Tuesday at 11am if that's ok!

**Comment by bradreeder** [comment]
https://hangouts.google.com/call/n36tjsfgmrcf5bjfwigwxbwncue

@emilyb7 @shiryz @amgoforth @MHemsley
