### ISSUE TITLE
Template for progress summary page

### ISSUE THREAD

**Issue by shiryz** [CYPIAPT-LNDSE/goals-app#20]
- [x] Back button.
- [x] Goals list button.
- [x] Title of the goal.
- [x] sliding animation, see #33

**Comment by amgoforth** [comment]
@shiryz  @emilyb7  In terms of flowers for each day of the week - this is a nice idea, but the flowers should only grow when the young person moves closer to their goal, and sometimes they move away from their goal, which will mean the flower diminishes.  Sometimes a young person will move away from their goal for a reason that is not their fault, and I am wondering what message a wilting flower sends the user?

**Comment by shiryz** [comment]
We were thinking to represent small progress (/no progress at all) with a seed or maybe a sprout, which will still show that the flower is growing.
If the person decides to move away from a goal, we can add the option of remove the goal from the list in another iteration.

**Comment by amgoforth** [comment]
Just to be completely clear, a young person might score themselves on a goal at time 1 as 2, and at time 2 as 4, and then at time 3 as 1, so it's how to represent that movement, both forwards and backwards, without it feeling negative.
It might be that over the course of treatment there is no change in score on the goal at all, which would obvs be sad.

**Comment by shiryz** [comment]
![20170131_122927](https://cloud.githubusercontent.com/assets/22002193/22464980/5f2156b6-e7b1-11e6-8214-377d330d49a6.jpg)

this is the idea we were thinking of in terms of growth and small progress, we thought it would be friendlier than a graph. what do you think?

**Comment by amgoforth** [comment]
the thing is that, in some cases the young person would only rate themselves on their goal during their weekly session, rather than daily, so it would need to facilitate that.
I don't think we get the same depth of detail about changes over a period of time without a chart showing scores at each clinical session over the course of treatment.
