### ISSUE TITLE
Facebook auth issues

### ISSUE THREAD

**Issue by emilyb7** [CYPIAPT-LNDSE/goals-app#219]
nothing works like it should do :(

- cookie not being set properly
- sometimes i can't get to the app
- sometimes i can when i don't have a cookie

perhaps try a different auth strategy?

**Comment by emilyb7** [comment]
removing bell and going for a more basic implementation of oauth

**Comment by MHemsley** [comment]
Do you need a hand setting up auth?

**Comment by emilyb7** [comment]
@MHemsley we've had some problems, but think we've cracked it now! will let you know if we need more help. Thanks : )
