### ISSUE TITLE
Deploy to Heroku again

### ISSUE THREAD

**Issue by emilyb7** [CYPIAPT-LNDSE/goals-app#236]
Now that we have a working database connection and a facebook login, we should deploy to Heroku again.

In order to do this, we should create a new app with facebook so that we have separate app accounts / env variables for dev and production.

For production we need to whitelist the IP address of the heroku server.

**Comment by shiryz** [comment]
@MHemsley, do you think it'll be better to register the app from the Anna Freud account (if it exists), or should we create one ourselves?

**Comment by amgoforth** [comment]
@emilyb7 @shiryz @MHemsley is on holiday still I think.  I am really looking forwards to seeing the latest version!

**Comment by emilyb7** [comment]
thanks @amgoforth, we'll see if we can deploy what we have before the catchup tomorrow!

**Comment by emilyb7** [comment]
@amgoforth we've just updated!

https://polar-dawn-55555.herokuapp.com

it's possible that we'll be able to push a few more changes by tomorrow morning.

Stuff that's new:
- login page
- you can now login using facebook; our database saves your facebook ID so that the app knows if you're a new user or a returning user (it doesn't save your goals yet!! but that's coming very soon)
- confirmation message after adding a goal
- user menu
- log out link
- small line chart preview when reviewing a goal
- click on the blue title above the line chart to see a bigger version of the line chart
- click on any of the nodes on the chart to see details of the latest ratings
- rate-goal page has been moved around a bit based on feedback from you / noga + different plant avatars on the slider itself (not the animation though)
