### ISSUE TITLE
Can we arrange an update soon?

### ISSUE THREAD

**Issue by amgoforth** [CYPIAPT-LNDSE/goals-app#248]
@shiryz @emilyb7 @bradreeder

**Comment by bradreeder** [comment]
@amgoforth Thanks for getting in touch Alex, I was going to contact you today to ask the same and just recently spoke with Mark. Would there be a good time to chat this week?

**Comment by amgoforth** [comment]
@bradreeder I could do Friday at 2pm.  Would that work for you?

**Comment by bradreeder** [comment]
@amgoforth Sounds good -- catch up with you tomorrow!

**Comment by emilyb7** [comment]
👍🏻

**Comment by emilyb7** [comment]
@amgoforth we're on the regular hangout!
