### ISSUE TITLE
Create FB app for production

### ISSUE THREAD

**Issue by emilyb7** [CYPIAPT-LNDSE/goals-app#253]
No need to whitelist heroku after all...

Same settings as for dev

Need me, @shiryz and @MHemsley as collaborators...

Can be signed over to AFC as and when needed...

**Comment by emilyb7** [comment]
@MHemsley, I've created the app. If you give me your facebook user name I can add you as a collaborator!

**Comment by emilyb7** [comment]
alex is now admin too, can hand over to mark later

**Comment by MHemsley** [comment]
Can I check whether I need to do anything with this?

**Comment by emilyb7** [comment]
@MHemsley not necessarily, it's just so that you have control over the settings in the future. I think it makes more sense for you to be owner rather than me and Shireen.
