### ISSUE TITLE
Stand-up this morning (01.02.17)?

### ISSUE THREAD

**Issue by amgoforth** [CYPIAPT-LNDSE/goals-app#28]
@emilyb7 @shiryz

**Comment by amgoforth** [comment]
btw my mobile number is 07866 758880

**Comment by amgoforth** [comment]
@emilyb7 @shiryz If there is no stand-up, I would like to speak to you today to catch up.

**Comment by shiryz** [comment]
@amgoforth , we'll set a google hangouts (unless you prefer a phone call) for 10:30- 10:35, we're still waiting for Noga to join :smile: .

**Comment by amgoforth** [comment]
Great. Let's try hangouts.  If I drop out again today, we call fallback on phone.
