### ISSUE TITLE
User Story: As a user I want to see a list of goals I am working towards (screen 1)

### ISSUE THREAD

**Issue by emilyb7** [CYPIAPT-LNDSE/goals-app#3]
... so that I can keep my goals in mind at all times

## Small steps
- I receive a friendly greeting when I go to the app
- I can see up to 3 goals that I've already set myself at one glance
- I can see an icon representing each goal
- I can click a button to add a new goal

**Comment by shiryz** [comment]
![20170130_141853](https://cloud.githubusercontent.com/assets/22002193/22426533/77c6800c-e6f7-11e6-93b9-3e60de4e895a.jpg)

**Comment by amgoforth** [comment]
The goals would be worked towards over the course of treatment, which might be, e.g. 8 sessions of CBT, so not goals for today, as much as goals for now, or just - your goals

**Comment by amgoforth** [comment]
I like the idea of icons, but the goals will be very varied, and it might be tricky to have a library of icons big enough to be meaningful?

**Comment by emilyb7** [comment]
@amgoforth please excuse our very hurriedly written copy. You can take over the wording and we can say whatever you like!

As for the icons, I totally take your point. I think in the ideal scenario a user would be able to upload their own photo, but this is not possible without a backend. We were thinking of just 4 cute / fun icons for the MVP. We could tie these into the animation on screen 3 (the rate-your-progress one). If you would rather avoid icons altogether, that's fine.

**Comment by emilyb7** [comment]
@amgoforth 
<img width="300" alt="screen shot 2017-02-01 at 22 16 51" src="https://cloud.githubusercontent.com/assets/17532458/22528697/546e17c4-e8cc-11e6-830c-9b4e4720e948.png">

**Comment by amgoforth** [comment]
It's looking great!  Could it be called 'Grow' or does that not say enough?
