### ISSUE TITLE
Add transition between different pages on button clicks.

### ISSUE THREAD

**Issue by shiryz** [CYPIAPT-LNDSE/goals-app#44]
- [x] put all html files into one.
- [x] clicking on goal grow shows landing-page.
- [x] clicking on add goal hides landing-page and shows add-goal page.
- [x] clicking on a goal on the list shows the rate-goal  page and hides landing-page.
- [x] clicking on rate goes to progress review
- [x] clicking add goal , goes back to landing page.

**Comment by emilyb7** [comment]
@shiryz I've made changes to the HTM on the add goals page, need to make sure this is copied over to index.html on your branch...
