### ISSUE TITLE
Changes to copy

### ISSUE THREAD

**Issue by emilyb7** [CYPIAPT-LNDSE/goals-app#47]
@amgoforth I've summarised all proposed changes to copy here. If you have any other changes you'd like to see, please add them to this issue. We'll make sure it's done by this afternoon.

## add goals page
not all input to start with 'I will'

## rating page
change question to "How would you rate progress towards your goal today?"
@amgoforth this ideally needs to be a bit shorter

## name of app
change to "Grow" ?
I think we all prefer "GoalGrow", which was a suggestion from @nogainbar 
but I think it's your call @amgoforth 

## Goals on landing page

We currently have "Don't think so much" and so on. @amgoforth do you have 3 ideas for goals that you think are more realistic / appropriate?

**Comment by amgoforth** [comment]
Hi @emilyb7 @shiryz, I just want to say again how fantastic the prototype that you made is!  When I looked at the pages again, I remembered the gasp in the room last night (Thursday) when you demoed the animated flower growing!

I have some answered the queries about copy, below:

Add goals page
- I don't think we need text in the box...the cursor is enough

rating page
- "Right now, I rate my progress as... "

name of app
- I still think GrowGoal is a bit clunky, and that Grow nicely captures what the app is doing ASWELL as the function of goals.  I think it should be called 'Grow'.

Goals on landing page
- 1. To achieve my dreams
- 2. To know I am reaching my goals
- 3. To collaborate with others

**Comment by emilyb7** [comment]
@amgoforth doing this now! I just need someone to review the changes before the live version gets updated.

I had to make your goal ideas for the landing page a bit shorter as the longer copy messed up the layout completely (everything's a bit fragile at the moment). Here's what the new version will look like: 

<img width="780" alt="screen shot 2017-02-05 at 12 17 36" src="https://cloud.githubusercontent.com/assets/17532458/22626087/5efaffe4-eb9d-11e6-8138-07e8ea71dadc.png">

**Comment by emilyb7** [comment]
Deployed to github pages! 
https://cypiapt-lndse.github.io/goals-app/

thanks for merging @bradreeder :)
