### ISSUE TITLE
User Story: as a user I want to rate my progress towards a goal 

### ISSUE THREAD

**Issue by shiryz** [CYPIAPT-LNDSE/goals-app#5]
... so that I have a record to review with my clinician.

## Sub stories:

- I want to see which goal am I rating.
- I want a fun animated way to rate my progress.
- I want to submit (/save) my rating.
- I want a button that will take me back to the goals list.
- I want to record why my score changes so that I know what helps me move towards my goals, and what causes me to move further from it.

**Comment by shiryz** [comment]
![20170130_144541](https://cloud.githubusercontent.com/assets/22002193/22427473/37a9b968-e6fb-11e6-91ad-d8682fd8edcf.jpg)

**Comment by amgoforth** [comment]
A scale could work, but what about the circle that can be filled by enlarging or reducing the size of dot at its centre?

**Comment by shiryz** [comment]
We were thinking to have a growth scale so in this particular example we'll have a seed that would grow into a flower, and the scale would represent the numbers.

**Comment by emilyb7** [comment]
<img width="301" alt="screen shot 2017-02-01 at 22 16 25" src="https://cloud.githubusercontent.com/assets/17532458/22528718/68f26682-e8cc-11e6-9b75-16dbdb4c01fa.png">

**Comment by amgoforth** [comment]
I think the text needs to ask - how would you rate progress towards your goal today?  because they may be rating their progress over a number of days.  We might be able to make the question a bit snappier.  I'll think about it.
