### ISSUE TITLE
User Story: As a user I want to add a goal

### ISSUE THREAD

**Issue by shiryz** [CYPIAPT-LNDSE/goals-app#6]
## Sub Stories:

- I want to type in and/or voice record the goal I'll be working towards.
- I want to choose the icon for the new goal. (I would suggest that the user can take a picture to compliment the goal as the library of icons needed would be huge).
- I want to save (/submit) the new goal, and then see it in the list of goals.
- I want a back button that takes me back to the goals list.

**Comment by shiryz** [comment]
![20170130_144350](https://cloud.githubusercontent.com/assets/22002193/22427490/507e5818-e6fb-11e6-97f5-257355c8068b.jpg)

**Comment by emilyb7** [comment]
@amgoforth 

<img width="304" alt="screen shot 2017-02-01 at 22 16 34" src="https://cloud.githubusercontent.com/assets/17532458/22528684/436ab900-e8cc-11e6-8865-c0b4b51aa93e.png">

**Comment by amgoforth** [comment]
It's looking good!  Just a note - not all goals will start with 'I will...'

**Comment by shiryz** [comment]
@amgoforth, we'll get on that first thing in the morning, and these are currently placeholders, so please tell us of any text that needs to be changed.
