### ISSUE TITLE
UX Feedback

### ISSUE THREAD

**Issue by amgoforth** [CYPIAPT-LNDSE/goals-app#63]
Hi @shiryz @emilyb7 I've collated feedback so far into an excel sheet and uploaded it to resources, along with a video from one UX interview.  More to come.

**Comment by amgoforth** [comment]
Video was too big for Git so have uploaded to YouTube - access here - https://youtu.be/LvkXHzKJjQo

**Comment by emilyb7** [comment]
Hi @amgoforth, really interesting to read the feedback in the spreadsheet. Thanks for uploading that!

Could you clarify which view Helena means by "overview page"?

The youtube video's actually not working for me, so haven't been able to watch that. Maybe you can check it / try again?

**Comment by amgoforth** [comment]
Helena meant the final page that is a view of progress over time. Feedback has been that it isn't as clear as it could be, and as you indicated, on browsers other than Chrome, it looks skewed, etc.
