### ISSUE TITLE
Pitch Event Judging Criteria 8th Feb

### ISSUE THREAD

**Issue by CharlotteBarrett** [CYPIAPT-LNDSE/goals-app#64]
As in previous hackathons, apps will be judged on a demonstration of the app alongside a presentation that covers:

1.       Implementation (how easily they can be brought into use in a service, or with young people/families)
2.       Technical viability (how easily the idea can be fully executed from a technical standpoint)
3.       Need (what is the need for the app)
4.       Evidence-base (what is the evidence base for the thing that the app does)
5.       Product ownership (who will be owning the product and can they make the time available)
6.       User Experience (UX) feedback (feedback gathered during the week between 2nd and 9th February)
7.       Product roadmap (plans for further development)

**Comment by bradreeder** [comment]
Closed. Project was selected.
