### ISSUE TITLE
UX Feedback videos

### ISSUE THREAD

**Issue by amgoforth** [CYPIAPT-LNDSE/goals-app#66]
https://youtu.be/LvkXHzKJjQo

https://youtu.be/svoOODl8qng

**Comment by emilyb7** [comment]
first video - start at 18 seconds

second video - start at 28 seconds

**Comment by emilyb7** [comment]
Things for presentation:
- people like the clean design
- growth / nature are positive themes
- navigation needs some work, the feedback here has been really useful though!
- most people thought it would be useful, and a good alternative to paper
- we need to work on browser compatibility, and do much more testing
