### ISSUE TITLE
Estimates

### ISSUE THREAD

**Issue by emilyb7** [CYPIAPT-LNDSE/goals-app#68]
Notes here : https://docs.google.com/spreadsheets/d/1S11o79hW71MGjR5FMeJ1O2LSpzrzI9Y0DNOVXNVTHK8/edit?usp=sharing

**Comment by bradreeder** [comment]
These are underestimates in my opinion and will be revisited after @emilyb7 and @shiryz have had an opportunity to research into a few unknowns for this project.

**Comment by shiryz** [comment]
Closing, the app has been developed.
