### ISSUE TITLE
Schedule for sprint 1

### ISSUE THREAD

**Issue by emilyb7** [CYPIAPT-LNDSE/goals-app#69]
Below is an outline of our schedule for the first sprint:

Week commencing 6th March (FAC week 3):
**Tues 7th: meeting at 10am with AFC team + rest of day**
**Weds 8th: full day Emily, half day Shireen**
**Thurs 9th: full day**
**Fri 10th: half day Emily, full day Shireen**
Sat: day off
Sun: day off

Week commencing 13th March (FAC week 4):
**Mon 13th: full day**
**Tues 14th: full day**
Weds 15th: Emily travelling to Nazareth ☀️
**Thurs 16th: full day**
Fri - day off
Sat - day off
**Sun 19th - full day**

Week commencing 20th March: (FAC week 5)
**Mon 20th: full day**
**Tues 21st: full day**
**Weds 22nd: half day**

= 9 days + 2 half days each

After the first sprint we will most likely take a week's break. This will give us time to collect feedback.

Sprint 2 will start around 28th / 29th March.

**Comment by shiryz** [comment]
I'm not going to be working tomorrow friday the 10th but will be working on sunday 12th.
