### ISSUE TITLE
Resources for PWAs

### ISSUE THREAD

**Issue by emilyb7** [CYPIAPT-LNDSE/goals-app#74]
https://medium.com/@addyosmani/progressive-web-apps-with-react-js-part-i-introduction-50679aef2b12#.n10ttdozr

Things to note:
- we need an HTTPS server
- free SSL certificates available here: https://letsencrypt.org/
- To watch: https://developers.google.com/web/shows/cds/2015/deploying-https-the-green-lock-and-beyond-chrome-dev-summit-2015?hl=en
- Web app manifest on MDN: https://developer.mozilla.org/en-US/docs/Web/Manifest
- building a splash screen: https://developers.google.com/web/updates/2015/10/splashscreen?hl=en

**Comment by emilyb7** [comment]
https://codelabs.developers.google.com/codelabs/your-first-pwapp/#4

- this says local storage not recommended, instead use idb

**Comment by emilyb7** [comment]
So after a whole day of doing not much else...

My fave web app WeatherCat is now a PWA 🎉

https://weather-cat-react.herokuapp.com/

Well, kind of. It's a very messy implementation.

@shiryz, my initial conclusions:

- I'm still confused by caching and all the different kinds of client-side storage, there is lots to learn
- I would be a bit worried that we were doing things in a bad way and wouldn't know it. If we did this, we would def need help - @des-des ?  : )
- on the other hand, implementing some features of a PWA would probably be manageable, not sure if this is useful though?
- we would have to really plan out exactly how we were going to store data etc. The whole flow (postgres, local storage, application state) seems quite confusing to me right now
- it should be possible to add in the PWA functionality later on; but if we think that we are likely to want to do this, we would probs want to have at least some idea of how to do it in advance so that we know which bits of the code would be affected etc. and how to structure things

**Comment by des-des** [comment]
I am happy to lend a hand here, although I have not done any pwa stuff before..

One thing I would say is the redux will make you life easier.

**Comment by nogainbar** [comment]
@shiryz @emilyb7 @des-des Hope this can help, here is the link to the Google PWA workshop we had the good fortune to go to:
[PWA training resources](https://drive.google.com/drive/folders/0B9xlQg9XpugsNHhIWHFTbWhQTnM?usp=sharing)
Checkout especially the PDF titled- [progressive-web-apps-ilt-codelabs.pdf](https://drive.google.com/open?id=0B9xlQg9XpugsRDhVMGg4VDFOS2c) (the first one)

Also this is the [Codelabs](https://drive.google.com/open?id=0B9xlQg9XpugsNlFUYXRtRkdHelE) deck we worked from with zipped code and exercises.

If these links dont work for some reason, let me know and il just invite you on the google drive if you send me your email. :)

**Comment by nogainbar** [comment]
Also this [PDF](https://drive.google.com/open?id=0B9xlQg9XpugsTDlOZjNFalZhanc) might have some similarities but also added information.

I hope that this can answer some of your questions but more than happy to chat about it more tomorrow as well.. Sofia and Brad both did quite a lot with it as well as other FAC8 people who attended... you can always gitter someone like Gabriel for example, to ask specific questions in case you cant find the answers..

**Comment by MHemsley** [comment]
I don’t want to provide an overload of resources, but if you have any specific questions, I’m certainly happy to help.

I haven’t had a massive amount of experience developing PWA’s but have designed the architecture for a few, so happy to help out in that regard if helpful (especially where data flow is concerned)

We would also ask that you use https anyway no matter what
> On 4 Mar 2017, at 10:10, Emily Bertwistle <notifications@github.com> wrote:
> 
> splash
---------------------------------------------------------------------------------------
 This email has been scanned for email related threats and delivered safely by Mimecast.
 For more information please visit http://www.mimecast.com
---------------------------------------------------------------------------------------

**Comment by des-des** [comment]
From conversations I had with @shiryz  yesterday. I would advise caution of what you promise in terms of pwa features, these are enhancements and you should not let pressure to complete them eclipse doing a good job with your key functionality.
