### ISSUE TITLE
User Flow Designs

### ISSUE THREAD

**Issue by amgoforth** [CYPIAPT-LNDSE/goals-app#78]
![20170307_102544](https://cloud.githubusercontent.com/assets/17146118/23652194/dba703c8-031f-11e7-8efa-830f3bb63b2a.jpg)

**Comment by amgoforth** [comment]
![20170307_112851](https://cloud.githubusercontent.com/assets/17146118/23654529/faea3eea-0328-11e7-9777-7f7c2d038b98.jpg)

Thanks for the flow diagrams @emilyb7 .  They look great.  The diagram above is an added flow to editing and rating that allows changing the avatar for the goal, and adds details to the flow for editing the goal text.

**Comment by amgoforth** [comment]
@emilyb7 it might also worth making explicit that altering either the goal text or the avatar will not alter the historic scores.  We assume that anyone wanting to delete scores too will want to delete the goals.

Would it be easy to archive deleted goals?  At the very least, we should store all goals, both in use and deleted for research purposes.

**Comment by emilyb7** [comment]
issue of deleting goals resolved, see #82
