### ISSUE TITLE
Backend - set up database

### ISSUE THREAD

**Issue by shiryz** [CYPIAPT-LNDSE/goals-app#82]
- [x] write database sql files.
- [x] add tables to database.
- [x] deploy database on heoku.

**Comment by shiryz** [comment]
Database Schema:

Users table:

user_id | reference_to_user|
--------|---------------------|

Goals table:

goal_id| user_id| title| rating| icon|
--------|--------|-----|-------|------|

Ratings table:

rating_id| user_id| goal_id| rating| comment|
---------|---------|---------|-------|-----------|

**Comment by MHemsley** [comment]
Having seen @amgoforth comment this morning. If you want to represent deleted goals/ratings within the DB for research, I would just added a column for 'deleted' which would reference a boolean value, and then filter when calling it on the front-end

**Comment by emilyb7** [comment]
yeah, agree with what @MHemsley says about deleting

i think we should also add a created date to all 3 tables

**Comment by emilyb7** [comment]
should we make a table just for storing the urls of the avatar pics?

**Comment by shiryz** [comment]
Modified Goals table:

goal_id| user_id| title| rating| icon| deleted|
--------|--------|-----|-------|------|---------|
