### ISSUE TITLE
User can add a goal

### ISSUE THREAD

**Issue by shiryz** [CYPIAPT-LNDSE/goals-app#89]
- [x] add a new goal page (react component) with styling
- [x] add goal button triggers change of view
- [x] redux: handle state change as moving between steps
- [x] redux: handle state on text input / selecting avatar
- [x] redux: handle state as new goal added
- [x] prevent form submit if no input
- [ ] confirmation page
- [x] adding a goal links back to goals' list
- [x] implement new font clear sans medium for input field text

On form limit input to 50 characters to start with!

**Comment by emilyb7** [comment]
done except for confirmation page
