### ISSUE TITLE
What plants should we grow?

### ISSUE THREAD

**Issue by emilyb7** [CYPIAPT-LNDSE/goals-app#97]
Noga and I were thinking:
- flower (probably not pink though)
- cactus
- chili pepper
- pumpkin

what does everyone else think?

**Comment by nogainbar** [comment]
I like this combo, I will design the cactus today and also change the colour of the flower. :)

**Comment by emilyb7** [comment]
@nogainbar could we have the new cactus icon and the flower icon without the square background too?
